apiVersion: v1
kind: Service
metadata:
  name: nginx-testing
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
      nodePort: 31000
  selector:
    app: nginx-testing
  status:
    loadBalancer: {}
